$('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    nav:true,
    responsive:{
        300:{
            items:1.5
        },
        400:{
            items:1.85
        },
        500:{
            items:2.15
        },
        600:{
            items:2.25
        },
        700:{
            items:2.5
        },
        800:{
            items:3
        },
        900:{
            items:3.25
        },
        1000:{
            items:3.65
        }
    }
})